### ISSUE TITLE
Please can you fix KeyError?

### ISSUE THREAD

**Issue by apcoid** [brain4tech/telegram-bot-api-scripts#1]
line: 67
userchatid = newmessage['message']['chat']['id']
KeyError: 'message'

Thank you sir for your time ;)

**Comment by brain4tech** [comment]
Hi!
This issue mainly comes from using a (super) group or channel instead of a private chat. You can fix it by either putting everything from line 56 up to 77 in a try-catch statement, or by changing the values in in line 67-69 to the following:

- `chat `-> `from `(for group or private chat)
- `message `-> `channel_post `AND delete the variable `newmessage`, as you cannot record usernames in channels (for channels only!).

I hope this fixes the issues :D

**Comment by apcoid** [comment]
Thank you, the problem has been solved.
